<?php

namespace Esprit\produitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
    public function findByCategorie($id_cat)
		{
		
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
			->from('EspritproduitBundle:Article', 'a')
			->where('a.categorie = :id')
			->setParameter('id', $id_cat)
			
			;
			
			return $qb->getQuery()->getResult();
		}
}
